/**
 * Created by Kevin on 2020/12/17.
 */
var cookieList = [TENANT_CODE+"_TENANT", "SYS_TENANT", TENANT_CODE+"_LOGINUSER", TENANT_CODE+"_AUTHORITY_ID", TENANT_CODE+"_AUTHORITY_NAME", TENANT_CODE+"_USERNAME", TENANT_CODE+"_UID", TENANT_CODE+"_USER_ORG", TENANT_CODE+"_HEAD_IMG", TENANT_CODE+"_APPLICATION_CODE"];